---
Name: squareimage
---

SilverStripe\Assets\Image:
  extensions:
    - HudhaifaS\Image\Extension\SquareImagelExtension
    
SilverStripe\Assets\Storage\DBFile:
  extensions:
    - HudhaifaS\Image\Extension\SquareImagelExtension